version: '3.3'

networks:
  public:
    external:
      name: docker-standalone-webdev-ci-stack_default

services:
  web:
    container_name: web
    image: jtreminio/php-apache:5.6
    # image: jtreminio/php-apache:7.3 # choose your PHP version here
    labels:
      - traefik.http.routers.example-lamp-web.rule=Host(`example-lamp.localhost`)
    networks:
      - public
    volumes:
      - ./www:/var/www/
      - ./log:/var/log/
      - ./vhost.conf:/etc/apache2/sites-enabled/default.conf
    environment:
      - PHP.display_errors=On
      - PHP.error_reporting=-1
      - PHPFPM_XDEBUG=On
      - PHP_INI_SCAN_DIR=:/etc/php/extra-mods/  # Enable all optionnal modules: https://github.com/jtreminio/php-docker#installed-modules
      - FPM.security.limit_extensions=          # avoids "Access Denied" due to "RewriteRule ^(.*)$ index.php/$0 [QSA,L]"
      - PHP.cgi.fix_pathinfo=1                  # Avoids "Undefined Index 'PATH_INFO'" in FPM mode

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - public
    volumes:
      - ./db:/var/lib/mysql
      
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb       
    restart: always
    volumes:
      - "/sessions"
    labels:
      - traefik.http.routers.example-lamp-phpmyadmin.rule=Host(`pma.example-lamp.localhost`)
    networks:
      - public
